export const mockGameData = [
  {
    "id": 1,
    "name": "The Legend of Zelda",
    "release_year": 1986,
    "genres": "Action-Adventure",
    "involved_companies": ["Nintendo"],
    "platforms": ["NES"],
    "rating": 95,
    "age_rating": "E",
    "cover": "https://upload.wikimedia.org/wikipedia/en/4/41/Legend_of_zelda_cover_%28with_cartridge%29_gold.png",
    "summary": "Link embarks on a quest to rescue Princess Zelda.",
    "story": "Defeat Ganon and rescue the princess.",
    "similar_games": [2, 3, 4]
  },
  {
    "id": 2,
    "name": "The Legend of Zelda: Ocarina of Time",
    "release_year": 1998,
    "genres": "Action-Adventure",
    "involved_companies": ["Nintendo"],
    "platforms": ["Nintendo 64"],
    "rating": 99,
    "age_rating": "E",
    "cover": "https://upload.wikimedia.org/wikipedia/en/5/57/The_Legend_of_Zelda_Ocarina_of_Time.jpg",
    "summary": "A groundbreaking 3D adventure with time travel mechanics.",
    "story": "Link must stop Ganondorf from obtaining the Triforce.",
    "similar_games": [1, 3, 5]
  },
  {
    "id": 3,
    "name": "The Legend of Zelda: The Wind Waker",
    "release_year": 2002,
    "genres": "Action-Adventure",
    "involved_companies": ["Nintendo"],
    "platforms": ["GameCube"],
    "rating": 96,
    "age_rating": "E",
    "cover": "https://upload.wikimedia.org/wikipedia/en/7/79/The_Legend_of_Zelda_The_Wind_Waker.jpg",
    "summary": "A vibrant, cel-shaded take on the Zelda universe.",
    "story": "Link sails the seas to rescue his sister.",
    "similar_games": [1, 2, 4]
  },
  {
    "id": 4,
    "name": "The Legend of Zelda: Breath of the Wild",
    "release_year": 2017,
    "genres": "Action-Adventure",
    "involved_companies": ["Nintendo"],
    "platforms": ["Nintendo Switch", "Wii U"],
    "rating": 97,
    "age_rating": "E",
    "cover": "https://upload.wikimedia.org/wikipedia/en/c/c6/The_Legend_of_Zelda_Breath_of_the_Wild.jpg",
    "summary": "An open-world adventure in the expansive kingdom of Hyrule.",
    "story": "Link awakens to defeat Calamity Ganon.",
    "similar_games": [1, 2, 3]
  },
  {
    "id": 5,
    "name": "The Legend of Zelda: A Link to the Past",
    "release_year": 1991,
    "genres": "Action-Adventure",
    "involved_companies": ["Nintendo"],
    "platforms": ["SNES"],
    "rating": 95,
    "age_rating": "E",
    "cover": "https://upload.wikimedia.org/wikipedia/en/2/21/The_Legend_of_Zelda_A_Link_to_the_Past_SNES_Game_Cover.jpg",
    "summary": "A classic top-down adventure with parallel worlds.",
    "story": "Link must save the Seven Maidens and defeat Ganon.",
    "similar_games": [1, 2, 4]
  },
  {
    "id": 6,
    "name": "Super Mario Bros.",
    "release_year": 1985,
    "genres": "Platformer",
    "involved_companies": ["Nintendo"],
    "platforms": ["NES"],
    "rating": 95,
    "age_rating": "E",
    "cover": "https://upload.wikimedia.org/wikipedia/en/0/03/Super_Mario_Bros._box.png",
    "summary": "Mario's quest to save Princess Peach from Bowser.",
    "story": "Traverse the Mushroom Kingdom to rescue the princess.",
    "similar_games": [7, 8, 9]
  },
  {
    "id": 7,
    "name": "Super Mario 64",
    "release_year": 1996,
    "genres": "Platformer",
    "involved_companies": ["Nintendo"],
    "platforms": ["Nintendo 64"],
    "rating": 97,
    "age_rating": "E",
    "cover": "https://upload.wikimedia.org/wikipedia/en/6/6a/Super_Mario_64_box_cover.jpg",
    "summary": "The first 3D Mario game that set the standard for the genre.",
    "story": "Mario must rescue Princess Peach from Bowser again.",
    "similar_games": [6, 8, 9]
  },
  {
    "id": 8,
    "name": "Super Mario Galaxy",
    "release_year": 2007,
    "genres": "Platformer",
    "involved_companies": ["Nintendo"],
    "platforms": ["Wii"],
    "rating": 97,
    "age_rating": "E",
    "cover": "https://upload.wikimedia.org/wikipedia/en/7/76/SuperMarioGalaxy.jpg",
    "summary": "A space-themed adventure with unique gravity mechanics.",
    "story": "Mario travels across galaxies to save Peach from Bowser.",
    "similar_games": [6, 7, 9]
  },
  {
    "id": 9,
    "name": "Super Mario Odyssey",
    "release_year": 2017,
    "genres": "Platformer",
    "involved_companies": ["Nintendo"],
    "platforms": ["Nintendo Switch"],
    "rating": 97,
    "age_rating": "E",
    "cover": "https://upload.wikimedia.org/wikipedia/en/8/8d/Super_Mario_Odyssey.jpg",
    "summary": "A 3D platformer with open-world elements and new mechanics.",
    "story": "Mario must rescue Princess Peach from Bowser using Cappy.",
    "similar_games": [6, 7, 8]
  },
  {
    "id": 10,
    "name": "Donkey Kong",
    "release_year": 1981,
    "genres": "Platformer",
    "involved_companies": ["Nintendo", "Pax Softonica"],
    "platforms": ["Arcade", "NES", "Game Boy"],
    "rating": 90,
    "age_rating": "E",
    "cover": "https://upload.wikimedia.org/wikipedia/en/1/14/Donkey_Kong_flier.jpg",
    "summary": "Help Mario rescue his girlfriend from Donkey Kong.",
    "story": "Climb platforms to save Pauline from the giant ape.",
    "similar_games": [11, 12, 13]
  },
  {
    "id": 11,
    "name": "Donkey Kong Country",
    "release_year": 1994,
    "genres": "Platformer",
    "involved_companies": ["Rare", "Nintendo"],
    "platforms": ["SNES"],
    "rating": 93,
    "age_rating": "E",
    "cover": "https://upload.wikimedia.org/wikipedia/en/1/1a/Donkey_Kong_Country_SNES_cover.png",
    "summary": "A side-scrolling platformer with stunning graphics.",
    "story": "Donkey Kong and Diddy Kong reclaim their stolen bananas.",
    "similar_games": [10, 12, 13]
  },
  {
    "id": 12,
    "name": "Donkey Kong 64",
    "release_year": 1999,
    "genres": "Platformer",
    "involved_companies": ["Rare", "Nintendo"],
    "platforms": ["Nintendo 64"],
    "rating": 85,
    "age_rating": "E",
    "cover": "https://upload.wikimedia.org/wikipedia/en/a/ae/DonkeyKong64CoverArt.jpg",
    "summary": "A 3D platformer featuring multiple playable characters.",
    "story": "Donkey Kong and friends must save their island from King K. Rool.",
    "similar_games": [10, 11, 13]
  },
  {
    "id": 13,
    "name": "Donkey Kong Country Returns",
    "release_year": 2010,
    "genres": "Platformer",
    "involved_companies": ["Retro Studios", "Nintendo"],
    "platforms": ["Wii"],
    "rating": 89,
    "age_rating": "E",
    "cover": "https://upload.wikimedia.org/wikipedia/en/1/1f/Donkeykongcountryreturns.jpg",
    "summary": "A revival of the classic series with new gameplay.",
    "story": "Donkey Kong and Diddy Kong must reclaim their island.",
    "similar_games": [10, 11, 12]
  },
  {
    "id": 14,
    "name": "Metroid",
    "release_year": 1986,
    "genres": "Action-Adventure",
    "involved_companies": ["Nintendo"],
    "platforms": ["NES"],
    "rating": 90,
    "age_rating": "E",
    "cover": "https://upload.wikimedia.org/wikipedia/en/5/5d/Metroid_boxart.jpg",
    "summary": "Explore an alien world as bounty hunter Samus Aran.",
    "story": "Samus must defeat the Space Pirates and Ridley.",
    "similar_games": [15, 16, 17]
  },
  {
    "id": 15,
    "name": "Super Metroid",
    "release_year": 1994,
    "genres": "Action-Adventure",
    "involved_companies": ["Nintendo"],
    "platforms": ["SNES"],
    "rating": 96,
    "age_rating": "E",
    "cover": "https://upload.wikimedia.org/wikipedia/en/e/e4/Smetroidbox.jpg",
    "summary": "A landmark in the Metroid series with refined gameplay.",
    "story": "Samus returns to Zebes to rescue a baby Metroid.",
    "similar_games": [14, 16, 17]
  },
  {
    "id": 16,
    "name": "Metroid Prime",
    "release_year": 2002,
    "genres": "First-Person Shooter",
    "involved_companies": ["Retro Studios", "Nintendo"],
    "platforms": ["GameCube"],
    "rating": 97,
    "age_rating": "E",
    "cover": "https://upload.wikimedia.org/wikipedia/en/b/ba/MetroidPrimebox.jpg",
    "summary": "A 3D exploration game that redefined the series.",
    "story": "Samus investigates the mysterious planet Tallon IV.",
    "similar_games": [14, 15, 17]
  },
  {
    "id": 17,
    "name": "Metroid Fusion",
    "release_year": 2002,
    "genres": "Action-Adventure",
    "involved_companies": ["Nintendo"],
    "platforms": ["Game Boy Advance"],
    "rating": 93,
    "age_rating": "E",
    "cover": "https://upload.wikimedia.org/wikipedia/en/4/45/Metroid_Fusion_box.jpg",
    "summary": "A side-scrolling adventure with enhanced mechanics.",
    "story": "Samus must escape from a research station after an incident.",
    "similar_games": [14, 15, 16]
  },
  {
    "id": 18,
    "name": "Star Fox",
    "release_year": 1993,
    "genres": "Shooter",
    "involved_companies": ["Nintendo"],
    "platforms": ["SNES"],
    "rating": 89,
    "age_rating": "E",
    "cover": "https://upload.wikimedia.org/wikipedia/en/5/52/Star_Fox_SNES.jpg",
    "summary": "Pilot the Arwing to save the Lylat system.",
    "story": "Fox McCloud and his team battle against Andross.",
    "similar_games": [19, 20, 21]
  },
  {
    "id": 19,
    "name": "Star Fox 64",
    "release_year": 1997,
    "genres": "Shooter",
    "involved_companies": ["Nintendo"],
    "platforms": ["Nintendo 64"],
    "rating": 94,
    "age_rating": "E",
    "cover": "https://upload.wikimedia.org/wikipedia/en/6/63/StarFox64_N64_Game_Box.jpg",
    "summary": "A groundbreaking 3D rail shooter with voice acting.",
    "story": "Join Fox and friends on a mission against Andross.",
    "similar_games": [18, 20, 21]
  },
  {
    "id": 20,
    "name": "Star Fox: Assault",
    "release_year": 2005,
    "genres": "Shooter",
    "involved_companies": ["Namco", "Nintendo"],
    "platforms": ["GameCube"],
    "rating": 80,
    "age_rating": "E",
    "cover": "https://upload.wikimedia.org/wikipedia/en/c/c2/Assaultbox.jpg",
    "summary": "Combines on-foot combat with classic Arwing missions.",
    "story": "Fox and crew battle a new threat to the Lylat system.",
    "similar_games": [18, 19, 21]
  },
  {
    "id": 21,
    "name": "Star Fox Zero",
    "release_year": 2016,
    "genres": "Shooter",
    "involved_companies": ["Platinum Games", "Nintendo"],
    "platforms": ["Wii U"],
    "rating": 75,
    "age_rating": "E",
    "cover": "https://upload.wikimedia.org/wikipedia/en/0/0a/Star_Fox_Zero.jpg",
    "summary": "A return to form with new gameplay mechanics.",
    "story": "Join Fox on a new mission to save the Lylat system.",
    "similar_games": [18, 19, 20]
  },
  {
    "id": 22,
    "name": "F-Zero",
    "release_year": 1990,
    "genres": "Racing",
    "involved_companies": ["Nintendo"],
    "platforms": ["SNES"],
    "rating": 90,
    "age_rating": "E",
    "cover": "https://upload.wikimedia.org/wikipedia/en/9/9b/SNES_F-Zero_boxart.jpg",
    "summary": "A fast-paced futuristic racing game.",
    "story": "Compete in the F-Zero Grand Prix.",
    "similar_games": [23, 24, 25]
  },
  {
    "id": 23,
    "name": "F-Zero X",
    "release_year": 1998,
    "genres": "Racing",
    "involved_companies": ["Nintendo"],
    "platforms": ["Nintendo 64"],
    "rating": 89,
    "age_rating": "E",
    "cover": "https://upload.wikimedia.org/wikipedia/en/2/21/F-Zero_X_box_art.jpg",
    "summary": "A 3D racing experience with high-speed action.",
    "story": "Race against others in the F-Zero circuit.",
    "similar_games": [22, 24, 25]
  },
  {
    "id": 24,
    "name": "F-Zero: Maximum Velocity",
    "release_year": 2001,
    "genres": "Racing",
    "involved_companies": ["Nintendo"],
    "platforms": ["Game Boy Advance"],
    "rating": 85,
    "age_rating": "E",
    "cover": "https://upload.wikimedia.org/wikipedia/en/0/00/Fzmvpackshot_us.jpg",
    "summary": "A return to the high-speed racing of the F-Zero series.",
    "story": "Compete in a new F-Zero Grand Prix.",
    "similar_games": [22, 23, 25]
  },
  {
    "id": 25,
    "name": "F-Zero GX",
    "release_year": 2003,
    "genres": "Racing",
    "involved_companies": ["Amusement Vision", "Nintendo"],
    "platforms": ["GameCube"],
    "rating": 91,
    "age_rating": "E",
    "cover": "https://upload.wikimedia.org/wikipedia/en/6/66/F-Zero_GX_box_artwork.png",
    "summary": "The fastest and most challenging entry in the series.",
    "story": "Race against the best in the F-Zero universe.",
    "similar_games": [22, 23, 24]
  },
  {
    "id": 26,
    "name": "Kirby’s Dream Land",
    "release_year": 1992,
    "genres": "Platformer",
    "involved_companies": ["Hal Laboratory", "Nintendo"],
    "platforms": ["Game Boy"],
    "rating": 88,
    "age_rating": "E",
    "cover": "https://upload.wikimedia.org/wikipedia/en/6/6a/Kirbys-dream-land-gameboy-boxart.png",
    "summary": "The first game in the beloved Kirby series.",
    "story": "Help Kirby save Dream Land from King Dedede.",
    "similar_games": [27, 28, 29]
  },
  {
    "id": 27,
    "name": "Kirby’s Adventure",
    "release_year": 1993,
    "genres": "Platformer",
    "involved_companies": ["Hal Laboratory", "Nintendo"],
    "platforms": ["NES"],
    "rating": 92,
    "age_rating": "E",
    "cover": "https://upload.wikimedia.org/wikipedia/en/a/ae/Kirby%27s_Adventure_Coverart.png",
    "summary": "Kirby's first NES adventure with copy abilities.",
    "story": "Help Kirby recover his stolen star rods.",
    "similar_games": [26, 28, 29]
  },
  {
    "id": 28,
    "name": "Kirby 64: The Crystal Shards",
    "release_year": 2000,
    "genres": "Platformer",
    "involved_companies": ["HAL Laboratory", "Nintendo"],
    "platforms": ["Nintendo 64"],
    "rating": 85,
    "age_rating": "E",
    "cover": "https://upload.wikimedia.org/wikipedia/en/c/c1/Kirby64_box.jpg",
    "summary": "A 3D platformer that allows for copy ability combinations.",
    "story": "Kirby must save Ripple Star from Dark Meta Knight.",
    "similar_games": [26, 27, 29]
  },
  {
    "id": 29,
    "name": "Kirby: Nightmare in Dream Land",
    "release_year": 2002,
    "genres": "Platformer",
    "involved_companies": ["HAL Laboratory", "Nintendo"],
    "platforms": ["Game Boy Advance"],
    "rating": 88,
    "age_rating": "E",
    "cover": "https://assets1.ignimgs.com/2020/03/16/kirby-nightmare-in-dreamland---button-1584390982242.jpg?width=300&crop=1%3A1%2Csmart&auto=webp&dpr=2",
    "summary": "A remake of the classic Kirby game.",
    "story": "Kirby must save Dream Land from nightmares.",
    "similar_games": [26, 27, 28]
  },
  {
    "id": 30,
    "name": "Metal Gear",
    "release_year": 1987,
    "genres": "Action-Adventure",
    "involved_companies": ["Konami"],
    "platforms": ["MSX2", "NES"],
    "rating": 89,
    "age_rating": "M",
    "cover": "https://upload.wikimedia.org/wikipedia/en/b/bd/Metal_Gear_cover.jpg",
    "summary": "Infiltrate enemy territory to stop Metal Gear.",
    "story": "As Solid Snake, defeat the rogue mercenary group.",
    "similar_games": [31, 32, 33]
  },
  {
    "id": 31,
    "name": "Metal Gear Solid",
    "release_year": 1998,
    "genres": "Action-Adventure",
    "involved_companies": ["Konami"],
    "platforms": ["PlayStation"],
    "rating": 96,
    "age_rating": "M",
    "cover": "https://preview.redd.it/metal-gear-solid-eu-box-art-1-1-aspect-ratio-retroarch-v0-xtc65126nbtc1.png?auto=webp&s=8348e84b98edbca3dbad476193fca48ff90248d8",
    "summary": "A groundbreaking stealth action game with cinematic storytelling.",
    "story": "Stop Liquid Snake from launching a nuclear weapon.",
    "similar_games": [30, 32, 33]
  },
  {
    "id": 32,
    "name": "Metal Gear Solid 2: Sons of Liberty",
    "release_year": 2001,
    "genres": "Action-Adventure",
    "involved_companies": ["Konami"],
    "platforms": ["PlayStation 2"],
    "rating": 95,
    "age_rating": "M",
    "cover": "https://upload.wikimedia.org/wikipedia/en/6/6a/Metalgear2boxart.jpg",
    "summary": "A sequel that expanded on the gameplay and story of its predecessor.",
    "story": "Unravel the mysteries behind the Big Shell incident.",
    "similar_games": [30, 31, 33]
  },
  {
    "id": 33,
    "name": "Metal Gear Solid 3: Snake Eater",
    "release_year": 2004,
    "genres": "Action-Adventure",
    "involved_companies": ["Konami"],
    "platforms": ["PlayStation 2"],
    "rating": 96,
    "age_rating": "M",
    "cover": "https://m.media-amazon.com/images/I/51inygLTtVL._AC_.jpg",
    "summary": "A prequel that focuses on survival and stealth.",
    "story": "As Naked Snake, stop the Cold War from escalating.",
    "similar_games": [30, 31, 32]
  },
  {
    "id": 34,
    "name": "Death Stranding",
    "release_year": 2019,
    "genres": "Action",
    "involved_companies": ["Kojima Productions"],
    "platforms": ["PlayStation 4"],
    "rating": 85,
    "age_rating": "M",
    "cover": "https://upload.wikimedia.org/wikipedia/en/2/22/Death_Stranding.jpg",
    "summary": "A unique open-world game that focuses on connection.",
    "story": "Deliver packages in a post-apocalyptic world.",
    "similar_games": [35, 36, 37]
  },
  {
    "id": 35,
    "name": "Metal Gear Solid V: The Phantom Pain",
    "release_year": 2015,
    "genres": "Action-Adventure",
    "involved_companies": ["Konami"],
    "platforms": ["PlayStation 4", "Xbox One"],
    "rating": 91,
    "age_rating": "M",
    "cover": "https://upload.wikimedia.org/wikipedia/en/8/8f/Metal_Gear_Solid_V_The_Phantom_Pain_cover.png",
    "summary": "An open-world stealth game with a focus on player choice.",
    "story": "Vengeance is the motivation behind Big Boss's journey.",
    "similar_games": [34, 36, 37]
  },
  {
    "id": 36,
    "name": "Metal Gear Solid V: Ground Zeroes",
    "release_year": 2014,
    "genres": "Action-Adventure",
    "involved_companies": ["Konami"],
    "platforms": ["PlayStation 4", "Xbox One"],
    "rating": 79,
    "age_rating": "M",
    "cover": "https://upload.wikimedia.org/wikipedia/en/0/07/MGSV_Ground_Zeroes_boxart.jpg",
    "summary": "A prologue to Metal Gear Solid V with a focus on stealth.",
    "story": "Rescue hostages from a Cuban military base.",
    "similar_games": [34, 35, 37]
  },
  {
    "id": 37,
    "name": "Zone of the Enders",
    "release_year": 2001,
    "genres": "Action",
    "involved_companies": ["Konami"],
    "platforms": ["PlayStation 2"],
    "rating": 85,
    "age_rating": "T",
    "cover": "https://upload.wikimedia.org/wikipedia/en/8/8b/Zone_of_the_Enders_Cover.jpg",
    "summary": "A mech-based action game with fast-paced combat.",
    "story": "Pilot the Jehuty and save the world.",
    "similar_games": [34, 35, 36]
  },
  {
    "id": 38,
    "name": "Chrono Trigger",
    "release_year": 1995,
    "genres": "RPG",
    "involved_companies": ["Square"],
    "platforms": ["SNES"],
    "rating": 94,
    "age_rating": "E",
    "cover": "https://upload.wikimedia.org/wikipedia/en/a/a7/Chrono_Trigger.jpg",
    "summary": "A time-traveling RPG with multiple endings.",
    "story": "Save the world from Lavos by traveling through time.",
    "similar_games": [39, 40, 41]
  },
  {
    "id": 39,
    "name": "Final Fantasy VI",
    "release_year": 1994,
    "genres": "RPG",
    "involved_companies": ["Square"],
    "platforms": ["SNES"],
    "rating": 96,
    "age_rating": "E",
    "cover": "https://upload.wikimedia.org/wikipedia/en/0/05/Final_Fantasy_VI.jpg",
    "summary": "An epic tale of rebellion against an oppressive empire.",
    "story": "Join the Returners to take down the Empire.",
    "similar_games": [38, 40, 41]
  },
  {
    "id": 40,
    "name": "Final Fantasy VII",
    "release_year": 1997,
    "genres": "RPG",
    "involved_companies": ["Square"],
    "platforms": ["PlayStation"],
    "rating": 92,
    "age_rating": "T",
    "cover": "https://upload.wikimedia.org/wikipedia/en/c/c2/Final_Fantasy_VII_Box_Art.jpg",
    "summary": "A revolutionary RPG that popularized the genre.",
    "story": "Cloud Strife joins AVALANCHE to stop Shinra and Sephiroth.",
    "similar_games": [38, 39, 41]
  },
  {
    "id": 41,
    "name": "Final Fantasy VIII",
    "release_year": 1999,
    "genres": "RPG",
    "involved_companies": ["Square"],
    "platforms": ["PlayStation"],
    "rating": 87,
    "age_rating": "T",
    "cover": "https://upload.wikimedia.org/wikipedia/en/5/5d/Final_Fantasy_8_ntsc-front.jpg",
    "summary": "A romantic story set in a world of magic and warfare.",
    "story": "Squall and his friends fight against the sorceress Ultimecia.",
    "similar_games": [38, 39, 40]
  },
  {
    "id": 42,
    "name": "Castlevania",
    "release_year": 1986,
    "genres": "Action",
    "involved_companies": ["Konami"],
    "platforms": ["NES"],
    "rating": 90,
    "age_rating": "E",
    "cover": "https://upload.wikimedia.org/wikipedia/en/5/51/Castlevania_1_cover.png",
    "summary": "A gothic action game featuring Dracula and his monsters.",
    "story": "Simon Belmont must defeat Dracula to save the day.",
    "similar_games": [43, 44, 45]
  },
  {
    "id": 43,
    "name": "Castlevania: Symphony of the Night",
    "release_year": 1997,
    "genres": "Action-Adventure",
    "involved_companies": ["Konami"],
    "platforms": ["PlayStation"],
    "rating": 95,
    "age_rating": "T",
    "cover": "https://upload.wikimedia.org/wikipedia/en/c/cf/Castlevania_SOTN_PAL.jpg",
    "summary": "A landmark title in the Metroidvania genre.",
    "story": "Alucard must defeat Dracula and explore the castle.",
    "similar_games": [42, 44, 45]
  },
  {
    "id": 44,
    "name": "Castlevania: Aria of Sorrow",
    "release_year": 2003,
    "genres": "Action-Adventure",
    "involved_companies": ["Konami"],
    "platforms": ["Game Boy Advance"],
    "rating": 90,
    "age_rating": "T",
    "cover": "https://upload.wikimedia.org/wikipedia/en/a/ab/AriaofSorrowCover.jpg",
    "summary": "A new take on the series with RPG elements.",
    "story": "Soma Cruz must defeat Dracula's forces.",
    "similar_games": [42, 43, 45]
  },
  {
    "id": 45,
    "name": "Castlevania: Dawn of Sorrow",
    "release_year": 2005,
    "genres": "Action-Adventure",
    "involved_companies": ["Konami"],
    "platforms": ["Nintendo DS"],
    "rating": 89,
    "age_rating": "T",
    "cover": "https://upload.wikimedia.org/wikipedia/en/d/d5/Castlevania_Dawn_of_Sorrow_NA_Cover.jpg",
    "summary": "A direct sequel to Aria of Sorrow with new mechanics.",
    "story": "Soma must face new threats in Dracula's castle.",
    "similar_games": [42, 43, 44]
  },
  {
    "id": 46,
    "name": "Grand Theft Auto",
    "release_year": 1997,
    "genres": "Action-Adventure",
    "involved_companies": ["DMA Design"],
    "platforms": ["PlayStation", "PC"],
    "rating": 70,
    "age_rating": "M",
    "cover": "https://upload.wikimedia.org/wikipedia/en/e/e7/GTA_-_Box_Front.jpg",
    "summary": "The original game that started the franchise.",
    "story": "Complete missions while navigating a criminal underworld.",
    "similar_games": [47, 48, 49]
  },
  {
    "id": 47,
    "name": "Grand Theft Auto III",
    "release_year": 2001,
    "genres": "Action-Adventure",
    "involved_companies": ["DMA Design"],
    "platforms": ["PlayStation 2", "PC"],
    "rating": 95,
    "age_rating": "M",
    "cover": "https://upload.wikimedia.org/wikipedia/en/b/be/GTA3boxcover.jpg",
    "summary": "The game that popularized the open-world genre.",
    "story": "Take on the role of a silent protagonist in Liberty City.",
    "similar_games": [46, 48, 49]
  },
  {
    "id": 48,
    "name": "Grand Theft Auto: Vice City",
    "release_year": 2002,
    "genres": "Action-Adventure",
    "involved_companies": ["Rockstar Games"],
    "platforms": ["PlayStation 2", "PC"],
    "rating": 95,
    "age_rating": "M",
    "cover": "https://upload.wikimedia.org/wikipedia/en/c/ce/Vice-city-cover.jpg",
    "summary": "A story of crime and betrayal set in the 1980s.",
    "story": "Climb the criminal ladder in Vice City.",
    "similar_games": [46, 47, 49]
  },
  {
    "id": 49,
    "name": "Grand Theft Auto: San Andreas",
    "release_year": 2004,
    "genres": "Action-Adventure",
    "involved_companies": ["Rockstar Games"],
    "platforms": ["PlayStation 2", "PC"],
    "rating": 95,
    "age_rating": "M",
    "cover": "https://upload.wikimedia.org/wikipedia/en/c/c4/GTASABOX.jpg",
    "summary": "An expansive world and story of gang life.",
    "story": "CJ returns to Los Santos to restore his family's former glory.",
    "similar_games": [46, 47, 48]
  },
  {
    "id": 50,
    "name": "Tekken",
    "release_year": 1994,
    "genres": "Fighting",
    "involved_companies": ["Namco"],
    "platforms": ["PlayStation"],
    "rating": 82,
    "age_rating": "T",
    "cover": "https://upload.wikimedia.org/wikipedia/en/0/0e/Tekken_1_game_cover.jpg",
    "summary": "The first game in the iconic fighting franchise.",
    "story": "Compete in the King of Iron Fist Tournament.",
    "similar_games": [51, 52, 53]
  },
  {
    "id": 51,
    "name": "Tekken 3",
    "release_year": 1997,
    "genres": "Fighting",
    "involved_companies": ["Namco"],
    "platforms": ["PlayStation"],
    "rating": 96,
    "age_rating": "T",
    "cover": "https://sm.ign.com/t/ign_nordic/cover/t/tekken-3/tekken-3_bz7d.600.jpg",
    "summary": "One of the best fighting games of its time.",
    "story": "Enter the King of Iron Fist Tournament 3.",
    "similar_games": [50, 52, 53]
  },
  {
    "id": 52,
    "name": "Tekken 5",
    "release_year": 2004,
    "genres": "Fighting",
    "involved_companies": ["Namco"],
    "platforms": ["PlayStation 2"],
    "rating": 92,
    "age_rating": "T",
    "cover": "https://upload.wikimedia.org/wikipedia/en/a/ad/Tekken5Cover.jpg",
    "summary": "Revitalized the series with new mechanics and characters.",
    "story": "Fight to become the best fighter in the world.",
    "similar_games": [50, 51, 53]
  },
  {
    "id": 53,
    "name": "Tekken 7",
    "release_year": 2015,
    "genres": "Fighting",
    "involved_companies": ["Namco"],
    "platforms": ["PlayStation 4", "Xbox One"],
    "rating": 86,
    "age_rating": "T",
    "cover": "https://upload.wikimedia.org/wikipedia/en/1/17/Official_Tekken_7_Logo.jpg",
    "summary": "The latest in the series with an expanded roster.",
    "story": "Conclude the long-standing feud between the Mishima family.",
    "similar_games": [50, 51, 52]
  },
  {
    "id": 54,
    "name": "Fallout",
    "release_year": 1997,
    "genres": "RPG",
    "involved_companies": ["Interplay Entertainment", "Black Isle Studios"],
    "platforms": ["PC"],
    "rating": 85,
    "age_rating": "M",
    "cover": "https://upload.wikimedia.org/wikipedia/en/a/af/Fallout.jpg",
    "summary": "A post-apocalyptic RPG with open-world elements.",
    "story": "Survive in a nuclear wasteland while seeking the water chip.",
    "similar_games": [55, 56, 57]
  },
  {
    "id": 55,
    "name": "Fallout 3",
    "release_year": 2008,
    "genres": "RPG",
    "involved_companies": ["Bethesda Game Studios"],
    "platforms": ["PC", "PlayStation 3", "Xbox 360"],
    "rating": 91,
    "age_rating": "M",
    "cover": "https://m.media-amazon.com/images/I/51HW6HrUolL._AC_.jpg",
    "summary": "Revitalized the series with a first-person perspective.",
    "story": "Search for your father in a post-apocalyptic D.C.",
    "similar_games": [54, 56, 57]
  },
  {
    "id": 56,
    "name": "Fallout: New Vegas",
    "release_year": 2010,
    "genres": "RPG",
    "involved_companies": ["Obsidian Entertainment", "Bethesda Game Studios"],
    "platforms": ["PC", "PlayStation 3", "Xbox 360"],
    "rating": 89,
    "age_rating": "M",
    "cover": "https://upload.wikimedia.org/wikipedia/en/3/34/Fallout_New_Vegas.jpg",
    "summary": "An open-world RPG set in a rich, branching narrative.",
    "story": "Determine the fate of the Mojave wasteland.",
    "similar_games": [54, 55, 57]
  },
  {
    "id": 57,
    "name": "Fallout 4",
    "release_year": 2015,
    "genres": "RPG",
    "involved_companies": ["Bethesda Game Studios"],
    "platforms": ["PC", "PlayStation 4", "Xbox One"],
    "rating": 87,
    "age_rating": "M",
    "cover": "https://upload.wikimedia.org/wikipedia/en/7/70/Fallout_4_cover_art.jpg",
    "summary": "A vast open world filled with quests and exploration.",
    "story": "Search for your kidnapped son in the Commonwealth.",
    "similar_games": [54, 55, 56]
  },
  {
    "id": 58,
    "name": "The Witcher",
    "release_year": 2007,
    "genres": "RPG",
    "involved_companies": ["CD PROJEKT RED"],
    "platforms": ["PC"],
    "rating": 86,
    "age_rating": "M",
    "cover": "https://upload.wikimedia.org/wikipedia/en/b/b0/The_Witcher_EU_box.jpg",
    "summary": "A narrative-driven RPG with rich lore and choices.",
    "story": "Play as Geralt of Rivia, a monster hunter.",
    "similar_games": [59, 60, 61]
  },
  {
    "id": 59,
    "name": "The Witcher 2: Assassins of Kings",
    "release_year": 2011,
    "genres": "RPG",
    "involved_companies": ["CD PROJEKT RED"],
    "platforms": ["PC", "Xbox 360"],
    "rating": 88,
    "age_rating": "M",
    "cover": "https://upload.wikimedia.org/wikipedia/en/4/40/Witcher_2_cover.jpg",
    "summary": "A sequel that deepens the combat and story.",
    "story": "Geralt investigates a conspiracy surrounding a king's murder.",
    "similar_games": [58, 60, 61]
  },
  {
    "id": 60,
    "name": "The Witcher 3: Wild Hunt",
    "release_year": 2015,
    "genres": "RPG",
    "involved_companies": ["CD PROJEKT RED"],
    "platforms": ["PC", "PlayStation 4", "Xbox One"],
    "rating": 93,
    "age_rating": "M",
    "cover": "https://upload.wikimedia.org/wikipedia/en/0/0c/Witcher_3_cover_art.jpg",
    "summary": "An expansive RPG with a richly detailed world.",
    "story": "Find your missing adopted daughter in a war-torn world.",
    "similar_games": [58, 59, 61]
  },
  {
    "id": 61,
    "name": "Gwent: The Witcher Card Game",
    "release_year": 2018,
    "genres": "Card Game",
    "involved_companies": ["CD PROJEKT RED"],
    "platforms": ["PC", "PlayStation 4", "Xbox One"],
    "rating": 85,
    "age_rating": "T",
    "cover": "https://upload.wikimedia.org/wikipedia/en/f/fd/Gwent_cover_art.png",
    "summary": "A strategic card game set in The Witcher universe.",
    "story": "Battle opponents in a card game based on tactics.",
    "similar_games": [58, 59, 60]
  },
  {
    "id": 62,
    "name": "Resident Evil",
    "release_year": 1996,
    "genres": "Survival Horror",
    "involved_companies": ["Capcom"],
    "platforms": ["PlayStation"],
    "rating": 89,
    "age_rating": "M",
    "cover": "https://upload.wikimedia.org/wikipedia/en/a/a6/Resident_Evil_1_cover.png",
    "summary": "A survival horror game set in a haunted mansion.",
    "story": "Uncover the mysteries of the Spencer Mansion.",
    "similar_games": [63, 64, 65]
  },
  {
    "id": 63,
    "name": "Resident Evil 2",
    "release_year": 1998,
    "genres": "Survival Horror",
    "involved_companies": ["Capcom"],
    "platforms": ["PlayStation"],
    "rating": 89,
    "age_rating": "M",
    "cover": "https://m.media-amazon.com/images/I/71uKwThrbhL._AC_SL1476_.jpg",
    "summary": "A sequel that set the standard for survival horror.",
    "story": "Survive in Raccoon City amidst a zombie outbreak.",
    "similar_games": [62, 64, 65]
  },
  {
    "id": 64,
    "name": "Resident Evil 3: Nemesis",
    "release_year": 1999,
    "genres": "Survival Horror",
    "involved_companies": ["Capcom"],
    "platforms": ["PlayStation"],
    "rating": 85,
    "age_rating": "M",
    "cover": "https://m.media-amazon.com/images/I/81U-jUTcBHL._AC_SL1420_.jpg",
    "summary": "Escape Raccoon City while being hunted by Nemesis.",
    "story": "Jill Valentine fights for survival against a relentless foe.",
    "similar_games": [62, 63, 65]
  },
  {
    "id": 65,
    "name": "Resident Evil 4",
    "release_year": 2005,
    "genres": "Survival Horror",
    "involved_companies": ["Capcom"],
    "platforms": ["GameCube", "PlayStation 2"],
    "rating": 96,
    "age_rating": "M",
    "cover": "https://upload.wikimedia.org/wikipedia/en/d/d9/Resi4-gc-cover.jpg",
    "summary": "A revolutionary take on survival horror gameplay.",
    "story": "Leon Kennedy must rescue the president's daughter.",
    "similar_games": [62, 63, 64]
  },
  {
    "id": 66,
    "name": "Tomb Raider",
    "release_year": 1996,
    "genres": "Action-Adventure",
    "involved_companies": ["Core Design"],
    "platforms": ["PlayStation"],
    "rating": 88,
    "age_rating": "T",
    "cover": "https://upload.wikimedia.org/wikipedia/en/6/69/Tomb_Raider_%281996%29.png",
    "summary": "Join Lara Croft on her archaeological adventures.",
    "story": "Explore tombs and discover ancient artifacts.",
    "similar_games": [67, 68, 69]
  },
  {
    "id": 67,
    "name": "Tomb Raider: Legend",
    "release_year": 2006,
    "genres": "Action-Adventure",
    "involved_companies": ["Crystal Dynamics"],
    "platforms": ["PC", "PlayStation 3", "Xbox 360"],
    "rating": 85,
    "age_rating": "T",
    "cover": "https://upload.wikimedia.org/wikipedia/en/7/7b/Tomb_Raider_-_Legend.png",
    "summary": "An acclaimed entry that revitalized the franchise.",
    "story": "Lara searches for the truth about her mother's disappearance.",
    "similar_games": [66, 68, 69]
  },
  {
    "id": 68,
    "name": "Tomb Raider: Underworld",
    "release_year": 2008,
    "genres": "Action-Adventure",
    "involved_companies": ["Crystal Dynamics"],
    "platforms": ["PC", "PlayStation 3", "Xbox 360"],
    "rating": 84,
    "age_rating": "T",
    "cover": "https://upload.wikimedia.org/wikipedia/en/5/56/Tomb_Raider_-_Underworld.png",
    "summary": "A direct sequel that continued Lara's journey.",
    "story": "Lara seeks to uncover her past and her mother.",
    "similar_games": [66, 67, 69]
  },
  {
    "id": 69,
    "name": "Tomb Raider (2013)",
    "release_year": 2013,
    "genres": "Action-Adventure",
    "involved_companies": ["Crystal Dynamics"],
    "platforms": ["PC", "PlayStation 3", "Xbox 360"],
    "rating": 86,
    "age_rating": "M",
    "cover": "https://upload.wikimedia.org/wikipedia/en/f/f1/TombRaider2013.jpg",
    "summary": "A reboot that reinvigorated the series.",
    "story": "Survive on a mysterious island and uncover its secrets.",
    "similar_games": [66, 67, 68]
  },
  {
    "id": 70,
    "name": "GoldenEye 007",
    "release_year": 1997,
    "genres": "First-Person Shooter",
    "involved_companies": ["Rare"],
    "platforms": ["Nintendo 64"],
    "rating": 96,
    "age_rating": "T",
    "cover": "https://upload.wikimedia.org/wikipedia/en/3/36/GoldenEye007box.jpg",
    "summary": "A revolutionary FPS based on the James Bond film.",
    "story": "Take on the role of James Bond in various missions.",
    "similar_games": [71, 72, 73]
  },
  {
    "id": 71,
    "name": "Perfect Dark",
    "release_year": 2000,
    "genres": "First-Person Shooter",
    "involved_companies": ["Rare"],
    "platforms": ["Nintendo 64"],
    "rating": 97,
    "age_rating": "T",
    "cover": "https://upload.wikimedia.org/wikipedia/en/3/32/Perfect_dark_box.jpg",
    "summary": "A spiritual successor to GoldenEye with advanced gameplay.",
    "story": "Joanna Dark must uncover a conspiracy.",
    "similar_games": [70, 72, 73]
  },
  {
    "id": 72,
    "name": "GoldenEye 007 (2010)",
    "release_year": 2010,
    "genres": "First-Person Shooter",
    "involved_companies": ["n-Space"],
    "platforms": ["Wii", "Xbox 360"],
    "rating": 80,
    "age_rating": "M",
    "cover": "https://upload.wikimedia.org/wikipedia/en/f/f1/GoldenEye_007_2010_remake_box_art.png",
    "summary": "A remake of the classic with updated visuals.",
    "story": "Experience the world of James Bond in a modern setting.",
    "similar_games": [70, 71, 73]
  },
  {
    "id": 73,
    "name": "TimeSplitters 2",
    "release_year": 2002,
    "genres": "First-Person Shooter",
    "involved_companies": ["Free Radical Design"],
    "platforms": ["PlayStation 2", "Xbox", "GameCube"],
    "rating": 89,
    "age_rating": "T",
    "cover": "https://upload.wikimedia.org/wikipedia/en/6/6b/Timesplitters2.JPG",
    "summary": "A fun and fast-paced shooter with a time-travel theme.",
    "story": "Fight through various eras to stop a time-traveling threat.",
    "similar_games": [70, 71, 72]
  },
  {
    "id": 74,
    "name": "Conker's Bad Fur Day",
    "release_year": 2001,
    "genres": "Platformer",
    "involved_companies": ["Rare"],
    "platforms": ["Nintendo 64"],
    "rating": 92,
    "age_rating": "M",
    "cover": "https://upload.wikimedia.org/wikipedia/en/9/99/Conkersbfdbox.jpg",
    "summary": "A unique platformer with mature humor.",
    "story": "Join Conker on his wild and comedic adventures.",
    "similar_games": [75, 76, 77]
  },
  {
    "id": 75,
    "name": "Conker: Live & Reloaded",
    "release_year": 2005,
    "genres": "Platformer",
    "involved_companies": ["Rare"],
    "platforms": ["Xbox"],
    "rating": 85,
    "age_rating": "M",
    "cover": "https://upload.wikimedia.org/wikipedia/en/3/3f/Conker_-_Live_%26_Reloaded_Coverart.png",
    "summary": "An enhanced remake of the original game.",
    "story": "Experience Conker's antics in high-definition.",
    "similar_games": [74, 76, 77]
  },
  {
    "id": 76,
    "name": "Yooka-Laylee",
    "release_year": 2017,
    "genres": "Platformer",
    "involved_companies": ["Playtonic Games"],
    "platforms": ["PC", "PlayStation 4", "Xbox One"],
    "rating": 74,
    "age_rating": "E10+",
    "cover": "https://upload.wikimedia.org/wikipedia/en/a/ac/Yooka-Laylee_cover_art.jpg",
    "summary": "A spiritual successor to classic platformers.",
    "story": "Embark on a colorful adventure with Yooka and Laylee.",
    "similar_games": [74, 75, 77]
  },
  {
    "id": 77,
    "name": "Super Lucky's Tale",
    "release_year": 2017,
    "genres": "Platformer",
    "involved_companies": ["Playful Studios"],
    "platforms": ["PC", "PlayStation 4", "Xbox One"],
    "rating": 75,
    "age_rating": "E10+",
    "cover": "https://upload.wikimedia.org/wikipedia/en/b/b1/Super_Lucky%27s_Tale.jpg",
    "summary": "A family-friendly platformer filled with adventure.",
    "story": "Help Lucky save the day in a vibrant world.",
    "similar_games": [74, 75, 76]
  },
  {
    "id": 78,
    "name": "Pokemon Red and Blue",
    "release_year": 1996,
    "genres": "RPG",
    "involved_companies": ["Game Freak"],
    "platforms": ["Game Boy"],
    "rating": 87,
    "age_rating": "E",
    "cover": "https://www.pokemon.com/static-assets/content-assets/cms2/img/video-games/video-games/pokemon_red_blue/pokemon_red_blue_main_169.jpg",
    "summary": "The original games that started the Pokemon craze.",
    "story": "Become a Pokemon Trainer and catch them all.",
    "similar_games": [79, 80, 81]
  },
  {
    "id": 79,
    "name": "Pokemon Gold and Silver",
    "release_year": 1999,
    "genres": "RPG",
    "involved_companies": ["Game Freak"],
    "platforms": ["Game Boy Color"],
    "rating": 89,
    "age_rating": "E",
    "cover": "https://upload.wikimedia.org/wikipedia/en/thumb/4/4c/Pokémon_box_art_-_Gold_Version.png/440px-Pokémon_box_art_-_Gold_Version.png",
    "summary": "A direct sequel that expanded the Pokemon universe.",
    "story": "Continue your adventure in the Johto region.",
    "similar_games": [78, 80, 81]
  },
  {
    "id": 80,
    "name": "Pokemon Ruby and Sapphire",
    "release_year": 2002,
    "genres": "RPG",
    "involved_companies": ["Game Freak"],
    "platforms": ["Game Boy Advance"],
    "rating": 84,
    "age_rating": "E",
    "cover": "https://upload.wikimedia.org/wikipedia/en/thumb/b/be/PokemonRubySapphireBox.jpg/440px-PokemonRubySapphireBox.jpg",
    "summary": "Introduces double battles and new mechanics.",
    "story": "Explore the Hoenn region and battle new Pokemon.",
    "similar_games": [78, 79, 81]
  },
  {
    "id": 81,
    "name": "Pokemon Diamond and Pearl",
    "release_year": 2006,
    "genres": "RPG",
    "involved_companies": ["Game Freak"],
    "platforms": ["Nintendo DS"],
    "rating": 87,
    "age_rating": "E",
    "cover": "https://upload.wikimedia.org/wikipedia/en/thumb/2/2e/PokemonDiamondPearlBoxArt.jpg/440px-PokemonDiamondPearlBoxArt.jpg",
    "summary": "Introduces online trading and battles.",
    "story": "Journey through the Sinnoh region and capture new Pokemon.",
    "similar_games": [78, 79, 80]
  },
  {
    "id": 82,
    "name": "SoulCalibur",
    "release_year": 1998,
    "genres": "Fighting",
    "involved_companies": ["Namco"],
    "platforms": ["Dreamcast", "Arcade"],
    "rating": 93,
    "age_rating": "T",
    "cover": "https://assets-prd.ignimgs.com/2021/12/14/soulcalibur-1639521545469.jpg?width=300&crop=1%3A1%2Csmart&auto=webp&dpr=2",
    "summary": "A weapons-based fighting game that redefined the genre.",
    "story": "Fight for the legendary sword Soul Edge.",
    "similar_games": [83, 84, 85]
  },
  {
    "id": 83,
    "name": "SoulCalibur II",
    "release_year": 2002,
    "genres": "Fighting",
    "involved_companies": ["Namco"],
    "platforms": ["PlayStation 2", "GameCube", "Xbox"],
    "rating": 92,
    "age_rating": "T",
    "cover": "https://assets-prd.ignimgs.com/2022/09/07/soulcali2-1662570739107.jpg?width=300&crop=1%3A1%2Csmart&auto=webp&dpr=2",
    "summary": "A highly praised sequel with new characters.",
    "story": "Continue the fight for the Soul Edge.",
    "similar_games": [82, 84, 85]
  },
  {
    "id": 84,
    "name": "SoulCalibur III",
    "release_year": 2005,
    "genres": "Fighting",
    "involved_companies": ["Namco"],
    "platforms": ["PlayStation 2"],
    "rating": 84,
    "age_rating": "T",
    "cover": "https://upload.wikimedia.org/wikipedia/en/5/51/ScIIIbox.jpg",
    "summary": "Introduces new gameplay mechanics and characters.",
    "story": "A new chapter in the battle for Soul Edge.",
    "similar_games": [82, 83, 85]
  },
  {
    "id": 85,
    "name": "SoulCalibur IV",
    "release_year": 2008,
    "genres": "Fighting",
    "involved_companies": ["Namco"],
    "platforms": ["PlayStation 3", "Xbox 360"],
    "rating": 85,
    "age_rating": "T",
    "cover": "https://assets-prd.ignimgs.com/2022/04/17/sc41-1650238999509.jpg?width=300&crop=1%3A1%2Csmart&auto=webp&dpr=2",
    "summary": "Features online play and characters from Star Wars.",
    "story": "The battle for Soul Edge continues.",
    "similar_games": [82, 83, 84]
  },
  {
    "id": 86,
    "name": "Soul Blade",
    "release_year": 1996,
    "genres": "Fighting",
    "involved_companies": ["Namco"],
    "platforms": ["PlayStation", "Arcade"],
    "rating": 80,
    "age_rating": "T",
    "cover": "https://assets-prd.ignimgs.com/2022/08/17/soulblade-1660767542766.jpg?width=300&crop=1%3A1%2Csmart&auto=webp&dpr=2",
    "summary": "The predecessor to SoulCalibur with unique characters.",
    "story": "Fight to become the ultimate warrior.",
    "similar_games": [82, 83, 84]
  },
  {
    "id": 87,
    "name": "Fire Pro Wrestling: Combination Tag",
    "release_year": 1989,
    "genres": "Sports",
    "involved_companies": ["Human Entertainment"],
    "platforms": ["PC Engine"],
    "rating": 88,
    "age_rating": "E",
    "cover": "http://www.pcengine.co.uk/Images-Coverthumbs/TC-Fire_Pro_Wrestling.jpg",
    "summary": "A wrestling game that started the series.",
    "story": "Compete in wrestling matches with a diverse roster.",
    "similar_games": [88, 89, 90]
  },
  {
    "id": 88,
    "name": "Fire Pro Wrestling: Returns",
    "release_year": 2007,
    "genres": "Sports",
    "involved_companies": ["Spike"],
    "platforms": ["PlayStation 2"],
    "rating": 89,
    "age_rating": "E",
    "cover": "https://upload.wikimedia.org/wikipedia/en/7/70/Fire_Pro_Wrestling_Returns.jpg",
    "summary": "An enhanced version of the classic wrestling series.",
    "story": "Create and manage your wrestling promotion.",
    "similar_games": [87, 89, 90]
  },
  {
    "id": 89,
    "name": "Fire Pro Wrestling World",
    "release_year": 2017,
    "genres": "Sports",
    "involved_companies": ["Spike"],
    "platforms": ["PlayStation 4", "PC"],
    "rating": 85,
    "age_rating": "E",
    "cover": "https://www.spike-chunsoft.com/wp-content/uploads/FireProWrestlingWorld_FullGame_MasterArt.png",
    "summary": "The latest entry in the long-running series.",
    "story": "Build your wrestling federation and compete worldwide.",
    "similar_games": [87, 88, 90]
  },
  {
    "id": 90,
    "name": "Fire Pro Wrestling",
    "release_year": 2001,
    "genres": "Sports",
    "involved_companies": ["Spike"],
    "platforms": ["Game Boy Advance"],
    "rating": 83,
    "age_rating": "E",
    "cover": "https://upload.wikimedia.org/wikipedia/en/c/c6/Fire_Pro_Wrestling_cover.jpg",
    "summary": "A portable entry that retains the series' charm.",
    "story": "Experience wrestling action on the go.",
    "similar_games": [87, 88, 89]
  },
  {
    "id": 91,
    "name": "WWF No Mercy",
    "release_year": 2000,
    "genres": "Sports",
    "involved_companies": ["AKI Corporation", "Asmik Ace Entertainment"],
    "platforms": ["Nintendo 64"],
    "rating": 92,
    "age_rating": "T",
    "cover": "https://upload.wikimedia.org/wikipedia/en/9/90/NoMercyGameBox.jpg",
    "summary": "A beloved wrestling game known for its depth.",
    "story": "Compete in the ring with your favorite WWE stars.",
    "similar_games": [92, 93, 94]
  },
  {
    "id": 92,
    "name": "WCW/nWo Revenge",
    "release_year": 1998,
    "genres": "Sports",
    "involved_companies": ["AKI Corporation", "Asmik Ace Entertainment"],
    "platforms": ["Nintendo 64"],
    "rating": 91,
    "age_rating": "T",
    "cover": "https://upload.wikimedia.org/wikipedia/en/1/1d/WCWnWoRevengebox.jpg",
    "summary": "A classic wrestling game featuring WCW stars.",
    "story": "Join the nWo and battle in the ring.",
    "similar_games": [91, 93, 94]
  },
  {
    "id": 93,
    "name": "WWF WrestleMania 2000",
    "release_year": 1999,
    "genres": "Sports",
    "involved_companies": ["AKI Corporation", "Asmik Ace Entertainment"],
    "platforms": ["Nintendo 64"],
    "rating": 88,
    "age_rating": "T",
    "cover": "https://upload.wikimedia.org/wikipedia/en/6/69/Wwfwrestlemania2000n64.jpg",
    "summary": "An innovative wrestling game with various modes.",
    "story": "Experience the biggest matches in wrestling history.",
    "similar_games": [91, 92, 94]
  },
  {
    "id": 94,
    "name": "Virtual Pro Wrestling 64",
    "release_year": 1996,
    "genres": "Sports",
    "involved_companies": ["AKI Corporation", "Asmik Ace Entertainment"],
    "platforms": ["Nintendo 64"],
    "rating": 87,
    "age_rating": "E",
    "cover": "https://assets-prd.ignimgs.com/2023/03/09/virtualpro64-1678392747997.jpg?width=300&crop=1%3A1%2Csmart&auto=webp&dpr=2",
    "summary": "A wrestling game that paved the way for future titles.",
    "story": "Step into the ring and compete with wrestlers.",
    "similar_games": [91, 92, 93]
  },
  {
    "id": 95,
    "name": "Virtual Pro Wrestling 2",
    "release_year": 2001,
    "genres": "Sports",
    "involved_companies": ["AKI Corporation", "Asmik Ace Entertainment"],
    "platforms": ["Nintendo 64"],
    "rating": 89,
    "age_rating": "E",
    "cover": "https://upload.wikimedia.org/wikipedia/en/7/75/Virtualprowrestling2.jpg",
    "summary": "A sequel that built upon its predecessor's success.",
    "story": "Continue your wrestling journey with more characters.",
    "similar_games": [91, 92, 93]
  },
  {
    "id": 96,
    "name": "WCW/NWO World Tour",
    "release_year": 1998,
    "genres": "Sports",
    "involved_companies": ["AKI Corporation", "Asmik Ace Entertainment"],
    "platforms": ["Nintendo 64"],
    "rating": 90,
    "age_rating": "E",
    "cover": "https://upload.wikimedia.org/wikipedia/en/c/c4/WCW_vs._nWo_-_World_Tour_Coverart.png",
    "summary": "A wrestling game that became a staple of its era.",
    "story": "Compete with your favorite wrestlers in various modes.",
    "similar_games": [91, 92, 93]
  },
  {
    "id": 97,
    "name": "WCW vs. The World",
    "release_year": 1997,
    "genres": "Sports",
    "involved_companies": ["The Man Breeze", "Asmik Ace Entertainment"],
    "platforms": ["PlayStation"],
    "rating": 87,
    "age_rating": "E",
    "cover": "https://upload.wikimedia.org/wikipedia/en/6/6e/WCW_vs._the_World.jpg",
    "summary": "A wrestling game that featured an international roster.",
    "story": "Battle against wrestlers from around the world.",
    "similar_games": [91, 92, 93]
  },
  {
    "id": 98,
    "name": "Marvel vs. Capcom: Clash of Super Heroes",
    "release_year": 1998,
    "genres": "Fighting",
    "involved_companies": ["Capcom"],
    "platforms": ["PlayStation", "Dreamcast", "Arcade"],
    "rating": 92,
    "age_rating": "T",
    "cover": "https://upload.wikimedia.org/wikipedia/en/b/b7/MvC_Cover_Art.png",
    "summary": "A crossover fighting game featuring Marvel characters.",
    "story": "Team up and battle iconic characters.",
    "similar_games": [99, 100, 101]
  },
  {
    "id": 99,
    "name": "Marvel vs. Capcom 2: New Age of Heroes",
    "release_year": 2000,
    "genres": "Fighting",
    "involved_companies": ["Capcom"],
    "platforms": ["PlayStation 2", "Dreamcast", "Arcade"],
    "rating": 93,
    "age_rating": "T",
    "cover": "https://assets-prd.ignimgs.com/2022/02/05/mvc2dc-sq-1644036776773.jpg?width=300&crop=1%3A1%2Csmart&auto=webp&dpr=2",
    "summary": "An acclaimed sequel with an expansive roster.",
    "story": "Engage in epic battles with Marvel and Capcom characters.",
    "similar_games": [98, 100, 101]
  },
  {
    "id": 100,
    "name": "Ultimate Marvel vs. Capcom 3",
    "release_year": 2011,
    "genres": "Fighting",
    "involved_companies": ["Capcom"],
    "platforms": ["PlayStation 3", "Xbox 360"],
    "rating": 88,
    "age_rating": "T",
    "cover": "https://upload.wikimedia.org/wikipedia/en/6/6d/UMvC3_Cover.jpg",
    "summary": "The ultimate crossover fighting game.",
    "story": "Fight against powerful heroes and villains.",
    "similar_games": [98, 99, 101]
  }
];


// Optionally, ensure the games are sorted
export const gameData = [...mockGameData].sort((a, b) => b.rating - a.rating); // Sort by rating